import type { Metadata } from "next"
import "@/styles/globals.css"
import locaLFont from "next/font/local"

const parastoo = locaLFont({
  src: [
    {
      path: "/fonts/Parastoo.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/Parastoo-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "/fonts/Parastoo-FD.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/Parastoo-Bold-FD.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-parastoo"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body
        className={`${parastoo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
